### PR TITLE
rt#76717: Support my_config, my_cache, my_download, my_publicshare

### PR DESCRIPTION
**Pull request by ioanrogers**
Hi,

I've rebased the patch from [rt#76717](https://rt.cpan.org/Ticket/Display.html?id=76717).
I don't have a Mac anymore, so I can't be certain that it still works :man_shrugging: :crossed_fingers:

### CODE REVIEW

**Comment by rehsack** [comment]
The tests should pass anyway - for all platforms

**Comment by dod38fr** [comment]
On my Debian system, the tests of this PR indeed fail once I've remove `xdg-user-dirs` package. This forces usage of Unix implementations which lack some methods like `my_config`, `my_download`...

HTH

**Comment by rehsack** [comment]
Maybe I was not explicit enough, thanks @dod38fr - as long as the PR passes on all platforms, it'll not merged. Furthermore - even when I'm not as strict as LKML, a reasonable and well formatted commit message is required anyway.

**Comment by rehsack** [comment]
I think, this is feedback outdated. Sorry. Please re-open again when having code for all supported operating systems.

**Pull request closed without merging**
